export const LOAD_STYLES = 'LOAD_STYLES';
export const UNLOAD_STYLES = 'UNLOAD_STYLES';
export const STORE_ACCESS_TOKEN = 'STORE_ACCESS_TOKEN';
export const REMOVE_ACCESS_TOKEN = 'REMOVE_ACCESS_TOKEN';

